// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkntBreak.Infrastructure.Data;

#nullable disable

namespace Skntbreak.Infrastructure.Migrations
{
    [DbContext(typeof(SkntbreakDbContext))]
    [Migration("20260220230951_FixedQueue")]
    partial class FixedQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skntbreak.Core.Entities.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserShiftId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserShiftId");

                    b.ToTable("Breaks");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.BreakChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BreakChats");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.BreakPoolDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableBreaks")
                        .HasColumnType("integer");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<int?>("Remaining10MinBreaks")
                        .HasColumnType("integer");

                    b.Property<int?>("Remaining20MinBreaks")
                        .HasColumnType("integer");

                    b.Property<int?>("Total10MinBreaks")
                        .HasColumnType("integer");

                    b.Property<int?>("Total20MinBreaks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBreaks")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("BreakPoolDays");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.BreakQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakRound")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserShiftId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserShiftId");

                    b.HasIndex("Status", "NotifiedAt")
                        .HasDatabaseName("IX_BreakQueues_Status_NotifiedAt");

                    b.HasIndex("WorkDate", "Group", "BreakRound", "Position")
                        .HasDatabaseName("IX_BreakQueues_WorkDate_Group_Round_Pos");

                    b.ToTable("BreakQueues");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDurationChoice")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShiftType")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.ShiftBreakTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ShiftBreakTemplates");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.UserShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId", "WorkDate")
                        .IsUnique();

                    b.ToTable("UserShifts");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.Break", b =>
                {
                    b.HasOne("Skntbreak.Core.Entities.UserShift", "UserShift")
                        .WithMany("Breaks")
                        .HasForeignKey("UserShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserShift");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.BreakChat", b =>
                {
                    b.HasOne("Skntbreak.Core.Entities.User", "User")
                        .WithMany("BreakChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.BreakQueue", b =>
                {
                    b.HasOne("Skntbreak.Core.Entities.UserShift", "UserShift")
                        .WithMany("QueueEntries")
                        .HasForeignKey("UserShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserShift");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.ShiftBreakTemplate", b =>
                {
                    b.HasOne("Skntbreak.Core.Entities.Schedule", "Schedule")
                        .WithMany("BreakTemplates")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.UserShift", b =>
                {
                    b.HasOne("Skntbreak.Core.Entities.Schedule", "Schedule")
                        .WithMany("UserShifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skntbreak.Core.Entities.User", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.Schedule", b =>
                {
                    b.Navigation("BreakTemplates");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.User", b =>
                {
                    b.Navigation("BreakChats");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("Skntbreak.Core.Entities.UserShift", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
